language: node_js
node_js:
  - '0.12'
notifications:
  email: false
script: npm run test
after_success: cat /home/travis/build/ichiriac/pdomap/coverage/lcov.info | /home/travis/build/ichiriac/pdomap/node_modules/coveralls/bin/coveralls.js
